#! /bin/sh
pkill dunst > /dev/null || dunst &
pgrep -x sxhkd > /dev/null || sxhkd &
pkill picom
picom -f --daemon --config "${HOME}/.config/picom/picom.conf" &

~/.config/polybar/launch.sh --material 2>/dev/null &

setxkbmap latam # set locale
vmware-user-suid-wrapper 2> /dev/null # allow shared clipboard with host
feh --bg-fill ~/Pictures/wallpaper.jpg # wallpaper
wmname LG3D & # fix for burp

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config focused_border_color '#de4d10' # Focused Orange
bspc config normal_border_color '#899c9c' # Normal cyan/white

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
